export enum Collections {
  LEADS = 'leads',
  USERS = 'users',
  PRODUCTS = 'products',
  STAFF = 'staff',
  USER_TOUCHPOINTS = 'userTouchpoints',
  USER_VAULTS = 'userVaults',
  ATTACHMENTS = 'attachments',
  USERS_BY_STAFF = 'usersByStaff',
  HOOKED_EVENTS = 'hookedEvents',
  USER_PRODUCTS = 'userProducts',
  OAUTH2_TOKENS = 'oauth2Tokens',
  USER_CALENDARS = 'userCalendars',
  USER_CALENDAR_EVENTS = 'userCalendarEvents',
  COMPANIES = 'companies',
  COMPANY_EMPLOYEES = 'companyEmployees',
  COMPANY_CLIENTS = 'companyClients',
  COMPANY_PROFILES = 'companyProfiles',
  COMPANY_DEPARTMENTS = 'companyDepartments',
  VAULTS = 'vaults',
}
