# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: On release created - Firebase deploy PROD

on:
  release:
    types: [published]

# on:
#   push:
#     tags:
#       - v*

env:
  SYS_ADMIN_EMAIL: 'manuel+psav@aconcagua.finance'
  NEW_USERS_TEMP_PASSWORD: '@Temp1234'

  TEST_ENV_KEY: 'TEST_ENV_VALUE'
  ENVIRONMENT: prod

  DOLAR_HOY_DOLAR_CRIPTO_DOM_QUERY: 'Dólar Oficial'
  AIRTABLE_API_KEY: '??'

  GOOGLE_OAUTH_CLIENT_ID: ${{secrets.GOOGLE_OAUTH_CLIENT_ID_PROD}}
  GOOGLE_OAUTH_CLIENT_SECRET: ${{secrets.GOOGLE_OAUTH_CLIENT_SECRET_PROD}}

  CONFIG_NETWORK_COLLECTION: 'configNetworks'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.19.0
          registry-url: https://npm.pkg.github.com/
      - run: npm ci --force --legacy-peer-deps
      - run: npm run prettier-ci
      - run: npm run lint-ci
      - run: npm run test-ci

      # ya lo hace el firebase.json
      # - run: npm run build

      - run: npm run deploy-ci
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{secrets.FIREBASE_SERVICE_ACCOUNT_KEY_PSAV}}
          FIREB_PROJECT_ID: 'aconcaguapsav'
          FIREB_API_KEY: 'AIzaSyDygVepLEVhHVnzVTwMOtbhOEvPg_hI6w4'
          FIREB_AUTH_DOMAIN: 'aconcaguapsav.firebaseapp.com'
          FIREB_STORAGE_BUCKET: 'aconcaguapsav.appspot.com'
          FIREB_MESSAGING_SENDER_ID: 860753192899
          FIREB_APP_ID: '1:860753192899:web:85929d7f0577a55be37f76'
          FIREB_MEASURAMENT_ID: 'G-46L2Y66TPG'

          GOOGLE_OAUTH_REDIRECT_URL: 'https://us-central1-aconcaguapsav.cloudfunctions.net/googleOAuth/oauth2callback'
          GOOGLE_CALENDAR_EVENT_WEBHOOK_URL: 'https://us-central1-aconcaguapsav.cloudfunctions.net/userCalendarEvents/google-event-webhook'

          API_USD_VALUATION: 'http://us-central1-aconcaguapsav.cloudfunctions.net/market/dolarOficial'
          API_TOKENS_VALUATIONS: 'http://us-central1-aconcaguapsav.cloudfunctions.net/market/tokensQuotes'
          API_EVALUATE_VAULTS: 'https://us-central1-aconcaguapsav.cloudfunctions.net/vaultsPolygon/evaluate'
          API_VAULT_ADMIN: 'https://us-central1-aconcaguapsav.cloudfunctions.net/vaultsPolygon/vaultAdmin'

      - run: npm run deploy-ci
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{secrets.FIREBASE_SERVICE_ACCOUNT_KEY}}
          FIREB_PROJECT_ID: 'aconcagua-365314'
          FIREB_API_KEY: 'AIzaSyCVjVkwUc63D9ES6AVwPCEahJHw1ky978Q'
          FIREB_AUTH_DOMAIN: 'aconcagua-365314.firebaseapp.com'
          FIREB_STORAGE_BUCKET: 'aconcagua-365314.appspot.com'
          FIREB_MESSAGING_SENDER_ID: 101110014661
          FIREB_APP_ID: '1:101110014661:web:137167add231676d4846ac'
          FIREB_MEASURAMENT_ID: 'G-4EP13854VS'

          GOOGLE_OAUTH_REDIRECT_URL: 'https://us-central1-aconcagua-365314.cloudfunctions.net/googleOAuth/oauth2callback'
          GOOGLE_CALENDAR_EVENT_WEBHOOK_URL: 'https://us-central1-aconcagua-365314.cloudfunctions.net/userCalendarEvents/google-event-webhook'

          API_USD_VALUATION: 'https://us-central1-aconcagua-365314.cloudfunctions.net/market/dolarOficial'
          API_TOKENS_VALUATIONS: 'http://us-central1-aconcagua-365314.cloudfunctions.net/market/tokensQuotes'
          API_EVALUATE_VAULTS: 'https://us-central1-aconcagua-365314.cloudfunctions.net/vaultsPolygon/evaluate'
          API_VAULT_ADMIN: 'https://us-central1-aconcagua-365314.cloudfunctions.net/vaultsPolygon/vaultAdmin'

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #         registry-url: https://npm.pkg.github.com/
  #     - run: npm ci

  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
