# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: On tag created - Firebase deploy QA

on:
  push:
    tags:
      - rc*

env:
  SYS_ADMIN_EMAIL: 'manuel@aconcagua.finance'
  NEW_USERS_TEMP_PASSWORD: '@Temp1234'

  TEST_ENV_KEY: 'TEST_ENV_VALUE'
  ENVIRONMENT: catedral-fb

  FIREB_PROJECT_ID: 'catedral-fb'
  FIREB_API_KEY: 'AIzaSyDTA7zMmjRD1L95x96s4r0WM9-JrDNNe_0'
  FIREB_AUTH_DOMAIN: 'catedral-fb.firebaseapp.com'
  FIREB_STORAGE_BUCKET: 'catedral-fb.appspot.com'
  FIREB_MESSAGING_SENDER_ID: 428867726479
  FIREB_APP_ID: '1:428867726479:web:ec0059f93c8b01b65354fa'
  FIREB_MEASURAMENT_ID: 'G-LKFV3L66D3'

  #AIRTABLE_API_KEY: '??'

  GOOGLE_OAUTH_CLIENT_ID: ${{secrets.GOOGLE_OAUTH_CLIENT_ID_QA}}
  GOOGLE_OAUTH_CLIENT_SECRET: ${{secrets.GOOGLE_OAUTH_CLIENT_SECRET_QA}}
  #GOOGLE_OAUTH_REDIRECT_URL: 'https://us-central1-catedral-fb.cloudfunctions.net/googleOAuth/oauth2callback'
  #GOOGLE_CALENDAR_EVENT_WEBHOOK_URL: 'https://us-central1-catedral-fb.cloudfunctions.net/userCalendarEvents/google-event-webhook'

  DOLAR_HOY_DOLAR_CRIPTO_DOM_QUERY: 'Dólar cripto'
  API_USD_VALUATION: 'http://us-central1-catedral-fb.cloudfunctions.net/scrapper/dolar-cripto'
  API_TOKENS_VALUATIONS: 'http://us-central1-catedral-fb.cloudfunctions.net/market/tokensQuotes'
  API_EVALUATE_VAULTS: 'http://us-central1-catedral-fb.cloudfunctions.net/vaultsPolygon/evaluate'
  API_VAULT_ADMIN: 'http://us-central1-catedral-fb.cloudfunctions.net/vaultsPolygon/vaultAdmin'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.17.1
          registry-url: https://npm.pkg.github.com/
      - run: npm ci --force --legacy-peer-deps
        env:
          NODE_AUTH_TOKEN: ${{secrets.VS_GITHUB_NPM_TOKEN}}
          # NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} este no tiee permisos en otro repo
          VS_GITHUB_NPM_TOKEN: ${{secrets.VS_GITHUB_NPM_TOKEN}}
      - run: npm run prettier-ci
      - run: npm run lint-ci
      - run: npm run test-ci

      # ya lo hace el firebase.json
      # - run: npm run build

      - run: npm run deploy-ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.VS_GITHUB_NPM_TOKEN}}
          VS_GITHUB_NPM_TOKEN: ${{secrets.VS_GITHUB_NPM_TOKEN}}
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #         registry-url: https://npm.pkg.github.com/
  #     - run: npm ci

  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
